Add missing runtime dependency on python2-six
We already `BuildRequires` it so everything builds successfully but
execution on EPEL7 fails with the following error

    [root@60d227f15636 /]# tracer
    Traceback (most recent call last):
    File "/usr/bin/tracer", line 33, in <module>
	import tracer.main
    File "/usr/lib/python2.7/site-packages/tracer/__init__.py", line 3, in <module>
	from tracer.query import Query
    File "/usr/lib/python2.7/site-packages/tracer/query.py", line 19, in <module>
	from tracer.resources.tracer import Tracer
    File "/usr/lib/python2.7/site-packages/tracer/resources/tracer.py", line 24, in <module>
	from tracer.resources.system import System
    File "/usr/lib/python2.7/site-packages/tracer/resources/system.py", line 31, in <module>
	from tracer.resources.processes import Process
    File "/usr/lib/python2.7/site-packages/tracer/resources/processes.py", line 28, in <module>
	from six import with_metaclass
    ImportError: No module named six