Pass the whole application to the provided_by function, not just its name
It fixes the following traceback when --erased parameter is used

      File "/home/jkadlcik/git/tracer/tracer/resources/tracer.py", line 117, in trace_affected
        if self._erased and not self._PACKAGE_MANAGER.provided_by(a.name):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/jkadlcik/git/tracer/tracer/resources/PackageManager.py", line 63, in provided_by
        return self.package_managers[0].provided_by(app)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/jkadlcik/git/tracer/tracer/packageManagers/rpm.py", line 165, in provided_by
        process = app.instances[0]  # @TODO Reimplement for all processes
                  ^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'instances'