Print a user-friendly error when a xml file cannot be parsed
We can define custom applications and rules for example in
`~/.config/tracer/applications.xml` and `~/.config/tracer/rules.xml`.
When there is an syntax error, we want to print something like

	Unable to parse /home/jkadlcik/.config/tracer/rules.xml
	Hint: not well-formed (invalid token): line 4, column 0

Instead of

	File "/usr/lib64/python3.9/xml/dom/minidom.py", line 1998, in parseString
		return expatbuilder.parseString(string)
	File "/usr/lib64/python3.9/xml/dom/expatbuilder.py", line 925, in parseString
		return builder.parseString(string)
	File "/usr/lib64/python3.9/xml/dom/expatbuilder.py", line 223, in parseString
		parser.Parse(string, True)
	xml.parsers.expat.ExpatError: not well-formed (invalid token): line 4, column 0